parameters:
    wassa_sms_envoi.sendsms.class: Wassa\Bundle\SmsEnvoiBundle\SendSms
 
services:
    wassa_sms_envoi.sendsms:
        class: "%wassa_sms_envoi.sendsms.class%"
        arguments: [%wassa_sms_envoi.api_key%, %wassa_sms_envoi.email%]