services:
    Wassa\SmsEnvoiBundle\SmsEnvoi:
        arguments: ["%wassa_sms_envoi.api_key%", "%wassa_sms_envoi.email%", "%wassa_sms_envoi.subtype%", "%wassa_sms_envoi.sender_label%"]
        public: true
